#!/bin/sh

if [[ ! -d "src/pages/posts" ]]; then
  npm run pub-code:link

else

    if [ $(find "src/pages/posts" -maxdepth 1 -type d ! -name "posts" ! -name ".git" | wc -l) -eq 0 ]; then
        echo "No posts found in 'src/pages/posts' >> Refreshing..."
        npm run pub-code:head
    fi

fi


npm run start --prefix scripts/symlink-repo