on:
  push:
    branches:
      - main
      - 'demo/**'

env: 
  GA_TAG_ID: ${{vars.GA_TAG_ID}}
  SITE: ${{secrets.SITE}}  
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --prefer-offline
          
      - name: Build
        env:
          GA_TAG_ID: ${{vars.GA_TAG_ID}}
        run: yarn build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=coder-rocks
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}