on:
  push:
    branches:
      - master
      - 'feature/gitactions'

env: 
  GA_KEY: ${{secrets.GA_KEY}}
  SITE: ${{secrets.SITE}}  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: yarn && yarn build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'coder.rocks'
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}